h1 python server.py > h1_server.out &
h1 python client.py > h1_client.out &
h2 python server.py > r2_server.out &
h2 python client.py > r2_client.out &
r1 python server.py > r1_server.out &
r1 python client.py > r1_client.out &
r2 python server.py > r2_server.out &
r2 python client.py > r2_client.out &
r3 python server.py > r3_server.out &
r3 python client.py > r3_client.out &
r4 python server.py > r4_server.out &
r4 python client.py > r4_client.out &
